# Generated by Django 6.0.7 on 2026-07-15 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_agendamento_criado_em_servico_ativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioFuncionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('intervalo_minutos', models.PositiveIntegerField(default=30, help_text='Intervalo usado para gerar os horários disponíveis.')),
                ('ativo', models.BooleanField(default=True)),
                ('barbeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_funcionamento', to='agendamentos.barbeiro')),
            ],
            options={
                'verbose_name': 'Horário de funcionamento',
                'verbose_name_plural': 'Horários de funcionamento',
                'ordering': ['barbeiro', 'dia_semana', 'hora_inicio'],
                'constraints': [models.UniqueConstraint(fields=('barbeiro', 'dia_semana'), name='horario_unico_por_barbeiro_e_dia')],
            },
        ),
    ]
