# Generated by Django 6.0.7 on 2026-07-16 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_horariofuncionamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoBarbeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedencia_cancelamento_horas', models.PositiveIntegerField(default=2, help_text='Quantidade mínima de horas antes do atendimento.', verbose_name='Antecedência para cancelamento')),
                ('antecedencia_reagendamento_horas', models.PositiveIntegerField(default=2, help_text='Quantidade mínima de horas antes do atendimento.', verbose_name='Antecedência para reagendamento')),
                ('antecedencia_agendamento_minutos', models.PositiveIntegerField(default=60, help_text='Exemplo: 60 significa que o cliente deve agendar com pelo menos 1 hora de antecedência.', verbose_name='Antecedência para novo agendamento')),
                ('dias_futuros_agendamento', models.PositiveIntegerField(default=30, help_text='Até quantos dias no futuro o cliente pode agendar.', verbose_name='Limite de dias futuros')),
                ('permitir_agendamento_mesmo_dia', models.BooleanField(default=True, verbose_name='Permitir agendamento no mesmo dia')),
                ('ativo', models.BooleanField(default=True, verbose_name='Configuração ativa')),
                ('barbeiro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao', to='agendamentos.barbeiro')),
            ],
            options={
                'verbose_name': 'Configuração do barbeiro',
                'verbose_name_plural': 'Configurações dos barbeiros',
            },
        ),
    ]
