# Generated by Django 6.0.7 on 2026-07-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0005_notificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('novo_agendamento', 'Novo agendamento'), ('cancelamento', 'Cancelamento'), ('reagendamento', 'Reagendamento'), ('status', 'Alteração de status'), ('lembrete', 'Lembrete de agendamento'), ('sistema', 'Sistema')], default='sistema', max_length=30),
        ),
    ]
