# Generated by Django 6.0.7 on 2026-07-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0006_alter_notificacao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaobarbeiro',
            name='antecedencia_lembrete_horas',
            field=models.PositiveIntegerField(default=24, help_text='Quantidade de horas antes do atendimento para gerar o lembrete.', verbose_name='Antecedência do lembrete'),
        ),
        migrations.AddField(
            model_name='configuracaobarbeiro',
            name='lembretes_ativos',
            field=models.BooleanField(default=True, help_text='Define se o sistema deve gerar lembretes internos para os agendamentos deste barbeiro.', verbose_name='Lembretes ativos'),
        ),
    ]
